//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teest.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grav
    {
        public int GravID { get; set; }
        public int KirkeID { get; set; }
        public string Fornavn { get; set; }
        public string Efternavn { get; set; }
        public System.DateTime Fødselsdato { get; set; }
        public System.DateTime Dødsdato { get; set; }
        public string Fødeby { get; set; }
        public string SidsteBopæl { get; set; }
        public string Stilling { get; set; }
        public string NærmestePårørende { get; set; }
        public string FacebookLink { get; set; }
        public string MyHeritageLink { get; set; }
        public string Biografi { get; set; }
        public string Uddannelse { get; set; }
        public string Karriere { get; set; }
        public string Bedrifter { get; set; }
    }
}
